datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.11.33:1521:orcl
    username: jsyd
    password: jsyd
jpa:
    hibernate:
        ddl-auto: update
        show-sql: true