spring:
  application:
    name: zuul-service
    nametext: 网关服务
    version: 1.0.0

endpoints:
  restart:
    enabled: true
  shutdown:
    #启用shutdown 可以通过post请求 http://微服务地址：port/shutdown 停止服务 需要结合安全验证才能在生产环境启动该功能
    enabled: true
    #禁用密码验证
    sensitive: false
  health:
    sensitive: false

zuul:
  #忽略自动生成微服务路径
  ignored-services: "*"
  #前缀
  prefix: /api
  routes:
    test:
      path: /test
      url: http://www.google.com
    ys:
      path: /ys/**
      serviceId: jsyd-ys-service
    bp:
      path: /bp/**
      serviceId: jsyd-bp-service
    gh:
      path: /gh/**
      serviceId: jsyd-gh-service
    jsyd-nz-service: /nz/**
    jsyd-ph-service: /ph/**

ribbon:
  eureka:
    enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # http://admin:123@localhost:8761/eureka/

server:
  port: 8762

logging:
  level:
    ROOT: INFO
    org.springframework.web: DEBUG