spring:
  application:
    name: zuul-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://@localhost:8761/eureka

zuul:
  routes:
    jsyd-ys-service:
      path: /ys/**
    jsyd-bp-service:
      path: /bp/**
    jsyd-nz-service:
      path: /nz/**
    jsyd-ph-service:
      path: /ph/**
    jsyd-gh-service:
      path: /gh/**

server:
  port: 8081
